import "@workspace/ui/globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Providers } from "../components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Shashivadan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={` ${geistSans.variable}  antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
